excessive-nesting-threshold = 4
too-many-arguments-threshold = 10
allowed-prefixes = ["..", "GPU", "Orca", "Local"]
allowed-idents-below-min-chars = ["..", "k", "f", "re", "id", "Ok", "'_"]
allowed-duplicate-crates = [
    "hashbrown",
    "indexmap",
    "windows-sys",
    "thiserror",
    "thiserror-impl",
    "bitflags",
    "heck",
    "syn",
]
