services:
  ide:
    build:
      context: ..
      dockerfile: ./gpu/Dockerfile
    privileged: true   # Docker-in-Docker needs this
    cgroup: host       # Allow setting resource constraints (e.g. memory, cpu) for containers
    environment:
    - RUST_BACKTRACE=1 # Display error trace on errors/panics
    volumes:
    - ${LOCAL_WORKSPACE_PATH}:${ENV_WORKSPACE_PATH} # source
    - docker_data:/var/lib/docker                   # Docker image cache
    - ${LOCAL_GIT_PATH}:${ENV_GIT_PATH}             # Base Git worktree history
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  docker_data:
