name: Build Diagram
runs:
  using: composite  
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install graphviz -y
        cargo install cargo-modules
    - name: Generate crate diagram
      run: |
        mkdir -p docs/images
        set -o pipefail
        cargo modules dependencies --lib --max-depth 0 \
          --no-uses --no-fns \
          --focus-on "
            orcapod::uniffi::{
              model::{Pod,PodJob,PodResult},
              store::filestore::LocalFileStore,
              orchestrator::{PodRun,docker::LocalDockerOrchestrator},
            }
          " \
          --layout dot | \
          dot -T svg > docs/images/orcapod_diagram.svg
    - uses: actions/upload-artifact@v4
      with:
        name: orcapod_diagram
        path: docs/images/orcapod_diagram.svg
        retention-days: 1
